name: Issues from todos
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  create_issues:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create issues from todos
        uses: alstr/todo-to-issue-action@v4.6.5
